---
- name: Verify
  hosts: all
  tasks:
    - name: test connection
      ping:

    - name: Verify that custom user is created
      getent: database=passwd key=gophish

    - name: Verify if NGINX service is running
      service:
        name: nginx
        state: started
        enabled: yes
      check_mode: yes
      register: nginx_service
      failed_when: (nginx_service is changed) or (nginx_service is failed)

    - name: Verify NGINX is up and running
      uri:
        url: http://localhost
        status_code: 200

    - name: Verify if postfix service is running
      service:
        name: postfix
        state: started
        enabled: yes
      check_mode: yes
      register: postfix_service
      failed_when: (postfix_service is changed) or (postfix_service is failed)

    - name: Verify if the gophish service is running
      service:
        name: gophish
        state: started
        enabled: yes
      check_mode: yes
      register: gophish_service
      failed_when: (gophish_service is changed) or (gophish_service is failed)

    - name: Check gophish phising page
      uri:
        url: http://127.0.0.1:8080
        status_code: 404

    - name: Check gophish admin page
      uri:
        url: https://127.0.0.1:3333/login
        status_code: 200
        validate_certs: no
