---
name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
      - '.ansible-lint'
      - '.yamllint'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
      - '.ansible-lint'
      - '.yamllint'
  schedule:
    - cron: "0 16 * * *"
  release:
    types: [prereleased, released]

jobs:
  default:
    name: Test default scenario.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - robertdebock/opensuse:latest
          - robertdebock/centos:8
          - robertdebock/alpine:3
          - robertdebock/archlinux:latest
          - robertdebock/debian:latest
          - robertdebock/ubuntu:focal
          - robertdebock/ubuntu:bionic
          - robertdebock/ubuntu:xenial
          - robertdebock/amazonlinux:latest
          - robertdebock/fedora:30
          - robertdebock/fedora:31
          - robertdebock/fedora:latest
          - robertdebock/redhat:latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule docker molecule-docker yamllint ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.image }}

  example_playbook_sqlite:
    name: Test playbook scenario.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - robertdebock/opensuse:latest
          - robertdebock/centos:8
          - robertdebock/alpine:3
          - robertdebock/archlinux:latest
          - robertdebock/debian:latest
          - robertdebock/ubuntu:focal
          - robertdebock/ubuntu:bionic
          - robertdebock/ubuntu:xenial
          - robertdebock/amazonlinux:latest
          - robertdebock/fedora:30
          - robertdebock/fedora:31
          - robertdebock/fedora:latest
          - robertdebock/redhat:latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule docker molecule-docker yamllint ansible-lint

      - name: Run Molecule full_example_playbook scenario tests.
        run: molecule test --scenario-name=example_playbook_sqlite
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.image }}

  release:
    name: Push release to Ansible Galaxy.
    if: github.event_name == 'release'
    needs:
      - default
      - example_playbook_sqlite
    runs-on: ubuntu-latest
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.0.3
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
